import { useCallback, useEffect, useState } from 'react';
import type { Appointment } from '../types/appointment';
import type { Patient } from '../types/patient';
import { facilityHeaders } from '../lib/facility';

export default function Appointments({ getToken, patients }: { getToken: () => Promise<string | null>; patients: Patient[]; facilityHeaders?: () => Record<string, string> }) {
  const [items, setItems] = useState<Appointment[]>([]); const [date, setDate] = useState('');
  const [open, setOpen] = useState(false); const [error, setError] = useState('');
  const load = useCallback(async () => { const token = await getToken(); const q = date ? `?date=${date}` : ''; const r = await fetch(`/api/appointments${q}`, { headers: { Authorization: `Bearer ${token}`, ...facilityHeaders() } }); const d = await r.json(); if (!r.ok) throw new Error(d.error || 'Unable to load appointments'); setItems(d.appointments || []); }, [date, getToken]);
  useEffect(() => { load().catch(e => setError(e.message)); }, [load]);
  async function save(e: React.FormEvent<HTMLFormElement>) { e.preventDefault(); const f = new FormData(e.currentTarget); const token = await getToken(); const r = await fetch('/api/appointments', { method: 'POST', headers: { Authorization: `Bearer ${token}`, 'Content-Type': 'application/json', ...facilityHeaders() }, body: JSON.stringify({ patient_id: f.get('patient_id'), scheduled_at: `${f.get('date')}T${f.get('time')}`, reason: f.get('reason') }) }); const d = await r.json(); if (!r.ok) { setError(d.error || 'Unable to schedule'); return; } setOpen(false); await load(); }
  async function cancel(id: string) { const token = await getToken(); await fetch(`/api/appointments/${id}`, { method: 'PUT', headers: { Authorization: `Bearer ${token}`, 'Content-Type': 'application/json', ...facilityHeaders() }, body: JSON.stringify({ status: 'cancelled' }) }); await load(); }
  return <section className="mt-10 rounded-xl border border-gray-800 bg-gray-900/50 p-6"><div className="flex flex-wrap items-center justify-between gap-3"><div><h2 className="text-xl font-semibold text-white">Appointments</h2><p className="text-sm text-gray-400">Manage your upcoming schedule.</p></div><div className="flex gap-2"><input type="date" value={date} onChange={e => setDate(e.target.value)} className="rounded bg-gray-800 p-2 text-white"/><button onClick={() => setOpen(true)} className="rounded bg-teal-600 px-4 py-2 font-medium text-white">Schedule</button></div></div>{error && <p className="mt-3 text-rose-400">{error}</p>}{open && <form onSubmit={save} className="mt-5 grid gap-3 rounded-lg bg-gray-800 p-4 md:grid-cols-5"><select name="patient_id" required className="rounded p-2"><option value="">Select patient</option>{patients.map(p => <option key={p.id} value={p.id}>{p.first_name} {p.last_name}</option>)}</select><input name="date" type="date" required className="rounded p-2"/><input name="time" type="time" required className="rounded p-2"/><input name="reason" placeholder="Reason for visit" className="rounded p-2"/><button className="rounded bg-emerald-600 px-3 text-white">Save</button></form>}<div className="mt-5 space-y-2">{items.map(a => <div key={a.id} className="flex flex-wrap items-center justify-between rounded-lg border border-gray-800 p-3 text-white"><div><b>{new Date(a.scheduled_at).toLocaleString()}</b><span className="ml-3 text-gray-300">{a.first_name} {a.last_name}</span><p className="text-sm text-gray-400">{a.reason || 'Appointment'} · {a.status}</p></div>{a.status === 'scheduled' && <button onClick={() => cancel(a.id)} className="text-sm text-rose-400">Cancel</button>}</div>)}{!items.length && <p className="text-gray-500">No appointments found.</p>}</div></section>;
}
